(* ::Package:: *)

(* r_e_derivation_self_energy.wl  --  Companion to                              *)
(*   Equation_Verification/Dual_Relativistic_Quantum_Mechanics_I.md (§III.D)    *)
(*                                                                              *)
(* Candidate-1 result (issue #64) — closed-form expression for r_e/r_0 by       *)
(* algebraic inversion of the DRQM I (III.22) cutoff equation, with QED a_e     *)
(* inherited from textbook calculations under hypothesis (ii).                  *)
(*                                                                              *)
(* WHAT THIS FILE ACTUALLY COMPUTES (iter-5 result):                            *)
(*   Cells 2–4 invert g_r(x) = 2[1 - 4/(2x+1)] = -2(1 + a_e) for x = r_e/r_0,   *)
(*   giving the closed form r_e/r_0 = (2 - a_e)/(2(2 + a_e)) for any a_e.       *)
(*   Plugging in QED loop-expansion a_e values produces a series converging to  *)
(*   the PR #62 triangulated value at 1.4σ above the precision floor.          *)
(*                                                                              *)
(* WHAT THIS FILE DOES NOT COMPUTE:                                             *)
(*   A first-principles derivation of r_e from the dual-Dirac framework's      *)
(*   one-loop self-energy diagram. Iters 1–4 attempted that approach and were   *)
(*   blocked by the absence of a published proper-time photon propagator in     *)
(*   the verified corpus (see STATE.md iter-3, referencing BS-§19 line 54).    *)
(*   Iter 5 pivoted to algebraic inversion + hypothesis-(ii) QED inheritance.   *)
(*   Cell 1 below and the Bethe-log heuristic at the end of the file are       *)
(*   scaffolding from the abandoned iter-1-4 approach, retained for the        *)
(*   provenance record (STATE.md), and clearly flagged as such.                *)
(*                                                                              *)
(* TARGET (PR #62 triangulation):  r_e/r_0 = 0.4994205099128317 ± 2.5e-13       *)
(* CODATA-full result (Cell 4):    r_e/r_0 = 0.4994205099131764                *)
(* Residual:                       3.45e-13 (1.38σ above the floor)            *)
(* 1-loop sub-result (Cell 2):     r_e/r_0 = 0.499419632156 (at a_e = α/(2π))  *)
(*                                                                              *)
(* HONEST SCOPE (Crocco rule #5).  The closed form is exact algebra. The       *)
(* numerical agreement comes from inheriting textbook QED a_e under hypothesis *)
(* (ii) — the dual framework's vertex correction is assumed to equal the       *)
(* standard Schwinger calculation. A dual-framework re-derivation of a_e from  *)
(* a proper-time photon propagator (hypothesis i) is OUT OF SCOPE for this PR  *)
(* and is the principal Tepper-blocker candidate identified in STATE.md iter-3.*)
(*                                                                              *)
(* SYMBOL CONVENTIONS  (per CLAUDE.md Wolfram MCP gotchas):                     *)
(*   ee     = electron charge          (NOT `e`, collides with Euler's number) *)
(*   potV   = scalar potential          (NOT `V`, collides with Vanadium)      *)
(*   alf    = fine-structure α                                                  *)
(*   m, c, hbar = standard                                                      *)
(*   r0     = classical electron radius e²/(m c²)                              *)
(*   re     = bound-state cutoff radius                                         *)
(*   capLambda = UV momentum cutoff Λ (used in vestigial Cell 1 only)          *)
(*   ssMin  = UV proper-time cutoff ≈ 1/Λ² (vestigial; iter-1-4)               *)
(*   uvec   = particle 3-velocity (proper-time) (vestigial; iter-1-4)          *)
(*   bb     = "collaborative" speed √(c² + u²) (vestigial; iter-1-4)           *)
(*                                                                              *)
(* CELL INVENTORY (as actually executed in iter-5)                              *)
(*   Cell 1 — VESTIGIAL: standard QED on-shell δm/m (Bjorken–Drell Eq. 10.59). *)
(*            Scaffolding from the abandoned iter-1-4 proper-time self-energy  *)
(*            approach; not used by Cells 2-4. Retained for provenance only.   *)
(*   Cell 2 — Algebraic inversion of (III.22) at 1-loop: solve g_r(x) =        *)
(*            -2(1 + α/(2π)) for x. Gives r_e/r_0 = (2 - α/(2π))/(4 + α/π).   *)
(*   Cell 3 — Convergence comparison: plug 1-loop and 2-loop a_e into closed   *)
(*            form r_e/r_0 = (2 - a_e)/(2(2 + a_e)); compare residuals vs     *)
(*            triangulated 0.4994205099128317.                                 *)
(*   Cell 4 — Higher-loop refinement: 3-loop, 4-loop, and CODATA-full a_e     *)
(*            convergence.                                                     *)
(*                                                                              *)
(* <!-- TODO: human reviews and fills in (Crocco substantive AI):               *)
(*      confirms that (a) the iter-5 pivot from proper-time self-energy to    *)
(*      algebraic inversion is the right disposition given BS-§19's            *)
(*      acknowledgment that no proper-time one-loop QED calculation exists in  *)
(*      the verified corpus, (b) hypothesis (ii) — inheriting Schwinger a_e —  *)
(*      is the intended reading, and (c) Cell 1 and the trailing Bethe-log    *)
(*      heuristic should remain in the file as flagged scaffolding rather     *)
(*      than be removed entirely. The pre-iter-5 cell-inventory plan          *)
(*      (proper-time photon propagator with b-dispersion, bound-state matrix  *)
(*      element on Coulomb 1s) remains the open thread for hypothesis-(i)     *)
(*      candidate work — see issue #67 candidate-list. -->                    *)
(*                                                                              *)
(* Author: Trey Morris with Claude Opus 4.7.  Started: 2026-05-26.              *)


(* ========================================================================== *)
(* Cell 1 — VESTIGIAL: standard QED baseline (NOT USED by Cells 2-4)          *)
(* ========================================================================== *)
(*                                                                            *)
(* PROVENANCE.  This cell is scaffolding from the abandoned iter-1-4 proper- *)
(* time self-energy approach (STATE.md iter-4). It computes the standard QED *)
(* on-shell mass shift δm/m as a baseline that the *abandoned* dual          *)
(* derivation would have modified. Iter-5 pivoted away from that approach    *)
(* (no proper-time photon propagator in verified corpus, BS-§19 line 54);   *)
(* Cells 2-4 below use a different method (algebraic inversion of III.22)   *)
(* that does not reference δm. This cell is retained for the provenance     *)
(* record only — re-running it confirms the abandoned approach's baseline   *)
(* but does not feed any number into the final closed-form result.          *)
(*                                                                            *)
(* The one-loop electron self-energy in standard QED is (Schwinger 1948,      *)
(* Bjorken–Drell §10.4):                                                      *)
(*                                                                            *)
(*   Σ(p) = -i ee² ∫ d⁴k/(2π)⁴  γᵘ [(p̸ - k̸ + m)/((p-k)² - m² + iε)] γᵤ      *)
(*                                       × [-1/(k² + iε)]                     *)
(*                                                                            *)
(* Using Schwinger proper-time:  i/(A - iε) = ∫₀^∞ ds e^{-isA}, the loop      *)
(* integral becomes a 2-parameter (s₁,s₂) integral over proper times.         *)
(* After Feynman parameter x = s₂/(s₁+s₂) and the photon-momentum Gaussian   *)
(* integral, the on-shell (p² = m²) mass shift is the textbook Schwinger      *)
(* result:                                                                    *)
(*                                                                            *)
(*   δm/m = (3 α / (4π)) [ Log(Λ²/m²) + 1/2 ]                                  *)
(*                                                                            *)
(* (Bjorken–Drell Eq. 10.59 in Gaussian units, α = ee²/(ħc).)                *)

ClearAll[alf, m, capLambda]; deltaMOverM = (3 alf/(4 Pi)) (Log[capLambda^2/m^2] + 1/2); Print["Cell 1 — Standard QED on-shell mass shift (Schwinger 1948 / Bjorken–Drell Eq. 10.59):"]; Print["  δm/m = ", deltaMOverM]; Print["  At α = 1/137.036, Λ/m = 1 (Bethe NR cutoff): δm/m ≈ ", N[deltaMOverM /. {alf -> 1/137.036, capLambda -> 1, m -> 1}, 6]];

(* Expected output  (✅ confirmed by Wolfram MCP, 2026-05-26):                *)
(*   delta m/m (symbolic) = (3 alf (1/2 + Log[capLambda^2/m^2])) / (4 Pi)     *)
(*   at alf=1/137.036, capLambda/m=1: 0.000871057                             *)
(*   heuristic Log(L^2/m^2) at re/r0=0.5: 11.2268                              *)
(*   heuristic delta m/m: 0.0204294                                            *)
(*   natural 1-loop coupling alf/(4 Pi): 0.000580705                           *)
(*   ratio heuristic / natural: ~35.2                                          *)


(* ========================================================================== *)
(* Cell 2 — Dual framework: solving g_r(r_e) = -2(1+a_e) for r_e/r_0          *)
(* ========================================================================== *)
(*                                                                            *)
(* The (III.22) g-factor formula in DRQM I reads                               *)
(*   g_r(x) = 2 [1 - 4/(2 x + 1)],   x = r/r0                                  *)
(* with limit g_r(1/2) = -2 (tree Dirac, r = r0/2).                            *)
(*                                                                            *)
(* The experimental electron g-factor is g_e^expt = -2 (1 + a_e^expt) with    *)
(* a_e^expt = 0.00115965218059 (CODATA-2018).  At one-loop QED, Schwinger     *)
(* (1948) computed a_e^(1) = alpha/(2 pi) from the vertex correction.  At     *)
(* two-loop, Sommerfeld–Petermann (1958) gave a_e^(2) = -0.328478 (alpha/pi)^2.*)
(*                                                                            *)
(* HYPOTHESIS (ii) for the dual framework (per iter-3 STATE.md):              *)
(* the proper-time one-loop vertex correction reproduces the standard QED     *)
(* Schwinger anomaly identically (photon propagator unchanged; all dual       *)
(* structure absorbed into the matter-side (II.3) "potential-in-the-mass"    *)
(* kernel, which at one-loop is formulation-independent).                     *)
(*                                                                            *)
(* The derivation is then:                                                     *)
(*   1. Compute a_e^(1) = alpha/(2 pi) in the dual framework  (= textbook,    *)
(*      under hypothesis ii — vertex correction is unchanged).                *)
(*   2. Insert into (III.22): solve g_r(r_e/r0) = -2(1 + a_e^(1)) for r_e/r0. *)
(*   3. The closed-form solution is                                            *)
(*          r_e/r0  =  (2 - alpha/(2 pi)) / (4 + alpha/pi)                    *)
(*      — exactly the Schwinger closed-form referenced in issue #64.          *)

ClearAll[alf, ae1, x, gr]; ae1 = alf/(2 Pi); gr[xVal_] := 2 (1 - 4/(2 xVal + 1)); soln = Solve[gr[x] == -2 (1 + ae1), x][[1]]; reOverR0OneLoop = x /. soln; Print["Cell 2 — Dual framework one-loop r_e/r_0:"]; Print["  symbolic: r_e/r_0 = ", Simplify[reOverR0OneLoop]]; Print["  closed-form check (matches (2-alpha/(2pi))/(4+alpha/pi)): ", FullSimplify[reOverR0OneLoop - (2 - ae1)/(2 (2 + ae1))]]; Print["  numerical (alpha=1/137.036), 18-digit: ", InputForm[N[reOverR0OneLoop /. alf -> 1/137.036, 18]]];

(* Expected output  (✅ confirmed by Wolfram MCP, 2026-05-26):                *)
(*   symbolic r_e/r_0 = -(alf - 4 Pi)/(2 alf + 8 Pi)                          *)
(*   closed-form check: 0                                                      *)
(*   numerical, 18-digit: 0.4994196321598656                                   *)


(* ========================================================================== *)
(* Cell 3 — Comparison to triangulated target and higher-loop refinement     *)
(* ========================================================================== *)
(*                                                                            *)
(* TARGET: r_e/r_0 = 0.4994205099128317 (PR #62 triangulated, sigma = 2.5e-13)*)
(*                                                                            *)
(* The 1-loop closed-form sits BELOW the triangulated target by ~8.78e-7.    *)
(* Including the 2-loop Sommerfeld–Petermann correction                       *)
(*   a_e^(2) = -0.328478 (alpha/pi)^2                                         *)
(* into the cutoff formula                                                    *)
(*   r_e/r_0 = (2 - a_e) / (2 (2 + a_e))                                      *)
(* with a_e = a_e^(1) + a_e^(2), shifts the prediction.                       *)

ClearAll[alf, ae1, ae2, aeTotal, reOverR0]; ae1 = alf/(2 Pi); ae2 = -0.328478 (alf/Pi)^2; aeTotal[order_] := Switch[order, 1, ae1, 2, ae1 + ae2]; reOverR0[order_] := (2 - aeTotal[order])/(2 (2 + aeTotal[order])); triang = 0.4994205099128317; alphaVal = 1/137.036; Print["Cell 3 — Comparison with triangulated target r_e/r_0 = ", triang, ":"]; Print["  Dirac tree (a_e=0):           r_e/r_0 = 1/2 = 0.5,                residual = ", InputForm[0.5 - triang]]; Print["  1-loop Schwinger:             r_e/r_0 = ", InputForm[N[reOverR0[1] /. alf -> alphaVal, 18]], ",  residual = ", InputForm[N[(reOverR0[1] /. alf -> alphaVal) - triang, 18]]]; Print["  2-loop (Sommerfeld a_e^(2)):  r_e/r_0 = ", InputForm[N[reOverR0[2] /. alf -> alphaVal, 18]], ",  residual = ", InputForm[N[(reOverR0[2] /. alf -> alphaVal) - triang, 18]]]; Print["  precision-floor improvement: 1-loop residual / 2-loop residual = ", InputForm[N[((reOverR0[1] /. alf -> alphaVal) - triang) / ((reOverR0[2] /. alf -> alphaVal) - triang), 5]]];

(* Expected output  (✅ confirmed by Wolfram MCP, 2026-05-26):                *)
(*   Dirac tree:        r_e/r_0 = 0.5,                  residual = 5.79e-4   *)
(*   1-loop Schwinger:  r_e/r_0 = 0.4994196321598656,   residual = -8.78e-7  *)
(*   2-loop Sommerfeld: r_e/r_0 = 0.4994205172822769,   residual = +7.37e-9  *)
(*   1-loop/2-loop ratio: ~-119, ie. 2-loop closer by ~120x                  *)
(*                                                                            *)
(* OUTCOME-MATRIX (per master #67):                                            *)
(*   Branch B confirmed at 1-loop: Schwinger closed-form reproduced.          *)
(*   Branch A *strongly* signalled at 2-loop: residual ~7e-9, three orders   *)
(*   of magnitude below 1-loop residual; full-precision (sigma=2.5e-13)      *)
(*   requires extending to 3-loop and beyond (a_e^(3) = 1.181241 (alpha/pi)^3).*)


(* ========================================================================== *)
(* Cell 4 — Full precision: 3-loop and beyond                                  *)
(* ========================================================================== *)

ClearAll[alf, ae1, ae2, ae3, ae4, aeTotal, reOverR0]; ae1 = alf/(2 Pi); ae2 = -0.328478965579193 (alf/Pi)^2; ae3 = 1.181241456587 (alf/Pi)^3; ae4 = -1.91245 (alf/Pi)^4; aeTotal[order_] := Switch[order, 1, ae1, 2, ae1 + ae2, 3, ae1 + ae2 + ae3, 4, ae1 + ae2 + ae3 + ae4]; reOverR0[order_] := (2 - aeTotal[order])/(2 (2 + aeTotal[order])); triang = 0.4994205099128317; alphaVal = 1/137.035999084; Print["Cell 4 — Higher-loop convergence (using CODATA alpha = 1/137.035999084):"]; Do[Print["  ", order, "-loop QED: r_e/r_0 = ", InputForm[N[reOverR0[order] /. alf -> alphaVal, 18]], ",  residual = ", InputForm[N[(reOverR0[order] /. alf -> alphaVal) - triang, 18]]], {order, 1, 4}]; aeCODATA = 0.00115965218059; reCODATA = (2 - aeCODATA)/(2 (2 + aeCODATA)); Print["  CODATA a_e (full): r_e/r_0 = ", InputForm[N[reCODATA, 18]], ",  residual = ", InputForm[N[reCODATA - triang, 18]]];

(* Expected output: 4-loop residual is ~2.5e-12 (~10σ above sigma=2.5e-13);  *)
(* CODATA-full a_e (which includes electroweak + hadronic + 5-loop QED)      *)
(* gives residual ~3.45e-13 (1.4σ above sigma) — see Cell 4 output.          *)
(*                                                                            *)
(* ========================================================================== *)
(* VESTIGIAL APPENDIX — abandoned iter-1-4 heuristic (NOT USED by Cells 2-4) *)
(* ========================================================================== *)
(*                                                                            *)
(* PROVENANCE.  The following paragraph records the iter-4 sanity check that *)
(* attempted to identify the QED UV cutoff Λ with the inverse bound-state    *)
(* cutoff radius r_e (the abandoned proper-time self-energy route's central  *)
(* identification). The factor-of-35 mismatch surfaced here is *the reason*  *)
(* the approach was abandoned at iter-5 in favour of algebraic inversion of  *)
(* (III.22). Nothing in Cells 2-4 above references the Λ↔r_e identification, *)
(* the proper-time photon propagator, or the Bethe-log structure. The text  *)
(* below is retained for the provenance record (cf. STATE.md iter-4) and    *)
(* for any future hypothesis-(i) candidate that revisits the abandoned      *)
(* approach with a derived proper-time photon propagator.                   *)
(*                                                                            *)
(* The Λ ↔ proper-time-cutoff correspondence:                                 *)
(*   ssMin = 1/Λ², so Log(Λ²/m²) = -Log(m² ssMin) = Log(1/(m² ssMin)).        *)
(*                                                                            *)
(* SANITY-CHECK CONNECTION TO r_e (heuristic, abandoned at iter-5):           *)
(*   If Λ is identified with the inverse bound-state cutoff radius via       *)
(*   Λ = hbar/r_e c (Compton-like), then Log(Λ²/m²) = -2 Log(r_e m c/ħ) =     *)
(*   -2 Log(r_e/λ_C) where λ_C = ħ/(mc).  Using r_0 = α λ_C:                  *)
(*     Log(Λ²/m²) = -2 Log((r_e/r_0) · α).                                    *)
(*   Setting (r_e/r_0) ≈ 1/2 gives Log(Λ²/m²) ≈ -2 Log(α/2) ≈ 11.23.          *)
(*   Then δm/m ≈ (3α/(4π)) · (11.23 + 0.5) ≈ 2.04e-2.                         *)
(*   The natural one-loop coupling α/(4π) ≈ 5.81e-4; the heuristic δm/m sits *)
(*   about 35× higher.                                                       *)
(*                                                                            *)
(* WHY THIS WAS ABANDONED.  The factor-of-35 mismatch was the iter-4         *)
(* signal that the simple Λ↔ħ/(r_e c) identification cannot be how the      *)
(* dual framework relates Λ to r_e — and that without a derived proper-time *)
(* photon propagator (which is not in the verified corpus), the abandoned   *)
(* approach has no way to close the gap. Iter 5 pivoted to algebraic        *)
(* inversion of (III.22), which sidesteps the cutoff-identification problem *)
(* entirely (the closed form r_e/r_0 = (2-a_e)/(2(2+a_e)) is independent of *)
(* how r_e relates to Λ).                                                   *)
(*                                                                            *)
(* A FUTURE hypothesis-(i) candidate that derives the proper-time photon    *)
(* propagator from the dual framework could revisit this identification.    *)
(* That is out of scope for this PR. *)
