(* ::Package:: *)

(* r_e_derivation_self_energy.wl  --  Companion to                              *)
(*   Equation_Verification/Dual_Relativistic_Quantum_Mechanics_I.md (§III.D)    *)
(*                                                                              *)
(* Candidate-1 scaffold (issue #64) — first-principles derivation of r_e from   *)
(* the dual-Dirac framework's one-loop electron self-energy diagram, formulated *)
(* as a Schwinger-like proper-time integral.                                    *)
(*                                                                              *)
(* TARGET (PR #62 triangulation):  r_e/r_0 = 0.4994205099128317 ± 2.5e-13       *)
(* SCHWINGER REFERENCE: (2 - α/(2π))/(4 + α/π) = 0.499419632156… (~1e-6 gap)    *)
(*                                                                              *)
(* HONEST SCOPE.  This file is built incrementally over multiple /loop          *)
(* iterations.  Each computational cell is structured to be re-executable       *)
(* against the Wolfram MCP as a single line (per CLAUDE.md gotcha #1).          *)
(*                                                                              *)
(* SYMBOL CONVENTIONS  (per CLAUDE.md Wolfram MCP gotchas):                     *)
(*   ee     = electron charge          (NOT `e`, collides with Euler's number) *)
(*   potV   = scalar potential          (NOT `V`, collides with Vanadium)      *)
(*   alf    = fine-structure α                                                  *)
(*   m, c, hbar = standard                                                      *)
(*   capLambda = UV momentum cutoff (Λ)                                         *)
(*   r0     = classical electron radius e²/(m c²)                              *)
(*   re     = bound-state cutoff radius (the quantity we want to derive)        *)
(*   ss     = Schwinger proper-time integration variable                        *)
(*   ssMin  = UV proper-time cutoff (≈ 1/Λ²)                                    *)
(*   uvec   = particle 3-velocity (proper-time)                                 *)
(*   bb     = "collaborative" speed √(c² + u²)                                  *)
(*                                                                              *)
(* CELL INVENTORY                                                               *)
(*   Cell 1 — Baseline: standard QED one-loop on-shell δm via Schwinger proper- *)
(*            time integral with hard UV cutoff Λ. (Bjorken–Drell Eq. 10.59.)  *)
(*   Cell 2 — (queued) Dual modification: replace c by b in photon-loop time    *)
(*            integration measure; track the b/c factor through to δm.          *)
(*   Cell 3 — (queued) Bound-state matrix element: evaluate δm on a Coulomb     *)
(*            1s-like wave-function with cutoff radius r; identify r=re from    *)
(*            renormalisation condition |δm(r_e)|/m = α/(4π).                  *)
(*   Cell 4 — (queued) Numerical comparison: r_e/r_0 vs 0.499420509912831 and   *)
(*            Schwinger closed-form 0.499419632156.                            *)
(*                                                                              *)
(* <!-- TODO: human reviews and fills in (Crocco substantive AI):               *)
(*      confirms the dual-framework photon propagator form between two          *)
(*      candidates: (i) Schwinger proper-time with b replacing c in the         *)
(*      dispersion k² = (ω/b)² - k², or (ii) textbook Feynman propagator        *)
(*      with the b/c factor absorbed into the source-coupling vertex.           *)
(*      Different choices give different numerical r_e/r_0 at the same order   *)
(*      in α; this is the principal Tepper-blocker candidate for issue #64. -->*)
(*                                                                              *)
(* Author: Trey Morris with Claude Opus 4.7.  Started: 2026-05-26.              *)


(* ========================================================================== *)
(* Cell 1 — Baseline standard QED one-loop on-shell mass shift                *)
(* ========================================================================== *)
(*                                                                            *)
(* The one-loop electron self-energy in standard QED is (Schwinger 1948,      *)
(* Bjorken–Drell §10.4):                                                      *)
(*                                                                            *)
(*   Σ(p) = -i ee² ∫ d⁴k/(2π)⁴  γᵘ [(p̸ - k̸ + m)/((p-k)² - m² + iε)] γᵤ      *)
(*                                       × [-1/(k² + iε)]                     *)
(*                                                                            *)
(* Using Schwinger proper-time:  i/(A - iε) = ∫₀^∞ ds e^{-isA}, the loop      *)
(* integral becomes a 2-parameter (s₁,s₂) integral over proper times.         *)
(* After Feynman parameter x = s₂/(s₁+s₂) and the photon-momentum Gaussian   *)
(* integral, the on-shell (p² = m²) mass shift is the textbook Schwinger      *)
(* result:                                                                    *)
(*                                                                            *)
(*   δm/m = (3 α / (4π)) [ Log(Λ²/m²) + 1/2 ]                                  *)
(*                                                                            *)
(* (Bjorken–Drell Eq. 10.59 in Gaussian units, α = ee²/(ħc).  The +1/2 is    *)
(* the Schwinger finite piece; some refs use a different finite scheme.)      *)
(*                                                                            *)
(* IMPORTANT: in this baseline cell, the *standard* speed-of-light c is used  *)
(* throughout — there is no b-dependence yet.  The dual modification enters   *)
(* in Cell 2.                                                                 *)

ClearAll[alf, m, capLambda]; deltaMOverM = (3 alf/(4 Pi)) (Log[capLambda^2/m^2] + 1/2); Print["Cell 1 — Standard QED on-shell mass shift (Schwinger 1948 / Bjorken–Drell Eq. 10.59):"]; Print["  δm/m = ", deltaMOverM]; Print["  At α = 1/137.036, Λ/m = 1 (Bethe NR cutoff): δm/m ≈ ", N[deltaMOverM /. {alf -> 1/137.036, capLambda -> 1, m -> 1}, 6]];

(* Expected output:                                                           *)
(*   Cell 1 — Standard QED on-shell mass shift (Schwinger 1948 / B–D 10.59):  *)
(*     δm/m = (3 α/(4π))(Log(Λ²/m²) + 1/2)                                    *)
(*     At α = 1/137.036, Λ/m = 1: δm/m ≈ 0.000871...                          *)
(*                                                                            *)
(* The Λ ↔ proper-time-cutoff correspondence:                                 *)
(*   ssMin = 1/Λ², so Log(Λ²/m²) = -Log(m² ssMin) = Log(1/(m² ssMin)).        *)
(*                                                                            *)
(* SANITY-CHECK CONNECTION TO r_e (heuristic, not derivation):                *)
(*   If Λ is identified with the inverse bound-state cutoff radius via       *)
(*   Λ = hbar/r_e c (Compton-like), then Log(Λ²/m²) = -2 Log(r_e m c/ħ) =     *)
(*   -2 Log(r_e/λ_C) where λ_C = ħ/(mc).  Using r_0 = α λ_C:                  *)
(*     Log(Λ²/m²) = -2 Log((r_e/r_0) · α).                                    *)
(*   Setting (r_e/r_0) ≈ 1/2 gives Log(Λ²/m²) ≈ -2 Log(α/2) ≈ 11.23.          *)
(*   Then δm/m ≈ (3α/(4π)) · (11.23 + 0.5) ≈ 2.04e-2.                         *)
(*   The natural one-loop coupling α/(4π) ≈ 5.81e-4; the heuristic δm/m sits *)
(*   about 35× higher.  Implication: the simple identification Λ↔hbar/(r_e c) *)
(*   over-estimates the radiative contribution by a factor of order 35 — the *)
(*   dual framework must either (a) provide a different identification of Λ *)
(*   with r_e, or (b) the bound-state matrix element supplies the missing *)
(*   factor (the Bethe-log structure replaces a flat UV log with a sum-over- *)
(*   states log, reducing the effective cutoff scale).  Both are pursued in *)
(*   Cells 2-3 of subsequent iterations. *)
