(* ::Package:: *)

(* r_e_Li2plus_joint_fit.wl  --  Companion to Quantum_Mechanics/Bethe_Salpeter/11_Li2plus_HydrogenicIon.md *)
(*                               and issue #78 (Li2+ Bethe-Salpeter Z-extension).                          *)
(*                                                                                                          *)
(* PURPOSE.  Tepper Gill's 2026-05-27 suggestion: apply the dual-theory / proper-time framework to the    *)
(* single-electron Li2+ hydrogenic ion (Z=3), predicting four precision observables (bound g-factor,       *)
(* 2S-2P Lamb shift, 2P fine structure, Li-7 1s hyperfine) and comparing to measurement.  The branch       *)
(* tests whether the framework's triangulated cutoff r_e/r_0 = 0.4994205099128317 (Z=1, PR #62) is        *)
(* Z-UNIVERSAL or Z-SCALED -- the Z-axis complement to PR #70's lepton-axis muon test.                     *)
(*                                                                                                          *)
(* GATING STRUCTURAL RESULT (STATE.md iter 4, from DRQM I Section III.D Eqs. III.22/III.23).               *)
(*   The (III.22) closed form r_e/r_0 = (2 - a_e)/(2(2 + a_e)) depends on exactly two inputs: the FREE-    *)
(*   electron anomaly a_e and r_0 = e^2/(m_e c^2).  NEITHER depends on nuclear charge Z.  The radiating    *)
(*   particle is the same electron at every Z, so r_e/r_0 is IDENTICAL at Z=1 and Z=3.  Contrast the      *)
(*   lepton axis (#70): there r_mu/r_0^mu != r_e/r_0^e at >57k sigma because BOTH a_l and r_0^l vary with *)
(*   lepton mass.  On the Z axis nothing varies => the cutoff is Z-INVARIANT by the framework's algebra.  *)
(*   Therefore (Z-i) universal cutoff is the framework-CORRECT reading; (Z-ii) Z-scaled cutoff is NOT      *)
(*   derivable; outcome-matrix Branch B is ruled out structurally.  Verdict lies between A and C.          *)
(*                                                                                                          *)
(* HONEST SCOPE / SUBSTANTIVE AI.  As with r_e_triangulation.wl, the three r_e-engaging observables       *)
(*   (#1 g-factor, #3 fine structure, #4 hyperfine) reduce to (g_s/-2)^n * textbook -- the anomaly piece  *)
(*   is back-fit, not an independent corroboration.  The ONE genuinely non-back-fit Z-dependence is the   *)
(*   Dirac binding correction to the bound g-factor (#1): g_bound = g_free[1 - (Z alpha)^2/3 - ...],      *)
(*   which is a real Z-scaling prediction from the (formulation-independent) Coulomb-Dirac structure.     *)
(*   Each Z-extension decision below is tagged "substantive choice" per Crocco (2026) compliance.         *)
(*                                                                                                          *)
(* WOLFRAM-MCP GOTCHAS (CLAUDE.md): single-line cells joined with ';'; aa = alpha, ae = anomaly, no bare  *)
(*   V or e as symbols.                                                                                     *)

(* ============================================================================================ *)
(* Section 0 -- constants                                                                        *)
(* ============================================================================================ *)

aa = 1/137.035999084;                 (* fine-structure constant (CODATA-2018) *)
ae = 0.00115965218059;                (* free-electron anomalous moment a_e = (|g_e| - 2)/2 *)
reOverR0 = 0.4994205099128317;        (* triangulated Z=1 cutoff, PR #62 -- Z-UNIVERSAL per gating result *)
mec2eV = 0.51099895000*10^6;          (* electron rest energy, eV *)
eV2MHz = 2.417989242*10^8;            (* 1 eV in MHz *)

(* ============================================================================================ *)
(* Section 1 -- Observable #1: bound-electron g-factor of Li2+ (Z=3)   [VERIFIED 2026-05-27]    *)
(* ============================================================================================ *)

(* SUBSTANTIVE CHOICE.  Framework prediction = (Dirac Coulomb binding g, genuinely Z-dependent) *)
(*   x (free anomaly from the Z-universal cutoff).  Binding from Breit (1928) point-nucleus 1s:  *)
(*   g_Dirac(1s) = (2/3)[1 + 2 Sqrt(1 - (Z alpha)^2)]; add free anomaly 2 a_e (cutoff supplies   *)
(*   a_e via III.22 at the Z-universal r_e/r_0).                                                  *)

gDirac1s[zz_] := (2/3)*(1 + 2*Sqrt[1 - (zz*aa)^2]);
gBound[zz_]   := gDirac1s[zz] + 2*ae;

(* Run: *)
(*   Print["Z alpha (Z=3) = ", 3*aa];                                                            *)
(*   Print["Dirac 1s binding g (Z=3) = ", gDirac1s[3]];                                          *)
(*   Print["+ free anomaly 2 a_e = ", 2*ae];                                                     *)
(*   Print["FRAMEWORK PREDICTION g_bound(7Li2+) = ", gBound[3]];                                 *)

(* RESULT (Wolfram MCP, 2026-05-27):                                                             *)
(*   Z alpha (Z=3)            = 0.0218921                                                         *)
(*   Dirac 1s binding g (Z=3) = 1.99968                                                           *)
(*   + free anomaly 2 a_e     = 0.0023193                                                         *)
(*   FRAMEWORK PREDICTION     g_bound(7Li2+) = 2.00200   (more precisely 2.0019998)              *)

(* PROVENANCE FINDING (settles STATE.md iter 4 flag).                                            *)
(*   The brief's cited observable-#1 value g_e^bound(7Li2+) = 2.0000251707(10) (attributed to    *)
(*   Sturm 2014 Nature 506, 467) is INCONSISTENT with hydrogenic Z=3 by ~2x10^-3.  Solving       *)
(*   gBound[z] == 2.0000251707 gives Z alpha = 0.0586 => Z ~ 8.04 (hydrogen-like OXYGEN), not    *)
(*   Z=3.  Moreover Sturm 2014 Nature 506,467 is the 12C5+ (Z=6) electron-mass measurement       *)
(*   (g(12C5+) ~ 2.00104), not a lithium measurement.  The brief's #1 entry is mis-attributed    *)
(*   on BOTH value and citation.  The correct hydrogenic 7Li2+ g-factor is ~2.00200.             *)
(*   ACTION: a genuine high-precision 7Li2+ bound-g measurement must be sourced before the       *)
(*   headline #1 comparison can be drafted; candidate hard-BLOCKED pending Tepper clarification.  *)

(* ============================================================================================ *)
(* Section 2 -- Observable #2: 2S-2P Lamb shift of Li2+ (Z=3)            [VERIFIED 2026-05-27]   *)
(* ============================================================================================ *)
(* SUBSTANTIVE CHOICE.  The framework's Lamb-shift route IS the textbook Bethe-1947 estimate      *)
(*   (BS-19/20: matrix elements, energy denominators, Bethe-log cutoff, mass-renormalisation all  *)
(*   formulation-independent).  So the Li2+ prediction = textbook Bethe-estimate at Z=3, which     *)
(*   inherits the standard ~4% residual vs the full measured value.  WEAK discriminator: leading   *)
(*   term g=2-symmetric => r_e enters only sub-leading => (Z-i) = (Z-ii) at the precision floor.   *)

lamH = 1057.845;     (* H Lamb shift, MHz (CODATA-2018) *)
lamLi = 62765.0;     (* measured Li2+ 2S-2P, MHz (Schiffer 1995 PRL 74, 2188) *)
betheBracket[zz_, cc_] := Log[1/(zz*aa)^2] + cc;   (* Z^4 prefactor x [log(1/(Z a)^2) + C] *)

(* Run:                                                                                           *)
(*   ratioMeas = lamLi/lamH;  (* 59.33 *)                                                         *)
(*   cc0 = cc /. First@Solve[3^4*(betheBracket[3,cc]/betheBracket[1,cc]) == ratioMeas, cc];       *)
(*   Print["bracket constant C = ", cc0];                  (* -1.626 *)                            *)
(*   Print["effective scaling vs Z^4 = ", betheBracket[3,cc0]/betheBracket[1,cc0]]; (* 0.7325 *)  *)
(*   fwFrac = 1016.0/lamH;                                  (* 0.9604 Z=1 Bethe-est fraction *)   *)
(*   Print["FRAMEWORK Li2+ Bethe-estimate = ", fwFrac*lamLi, " MHz"];                              *)

(* RESULT (Wolfram MCP, 2026-05-27):                                                              *)
(*   measured Li2+/H ratio   = 59.33   (naive Z^4 = 81; Bethe-log shrinks it by 0.7325)           *)
(*   bracket constant C      = -1.626  (~ -log k0(2,0) + self-energy/VP/Darwin constants)         *)
(*   FRAMEWORK Li2+ Lamb-est = 60 282 MHz  (residual -2483 MHz, ~3.96% -- SAME fraction as Z=1)   *)
(*   Verdict: reproduction-by-construction; the framework number is the textbook Bethe-estimate    *)
(*   with the standard residual; not an independent corroboration.                                 *)

(* ============================================================================================ *)
(* Section 3 -- Observable #3: 2P_3/2 - 2P_1/2 fine structure of Li2+    [STUB -- next iters]    *)
(* ============================================================================================ *)
(* Z-scaling: pure Z^4, delta E = m_e c^2 (Z alpha)^4 / 32 at n=2 -> ~887 GHz at Z=3.            *)
(*   GENUINE r_e discriminator via anomalous correction ((g_s-2)/2) delta E_leading.              *)
(*   PROVENANCE: brief's "~7367 MHz (Bayfield/Riis era)" is the wrong ion (helium-like Li+,       *)
(*   2 3P intervals), NOT hydrogenic Li2+ (~887 GHz).  Source a real hydrogenic measurement.      *)

(* ============================================================================================ *)
(* Section 4 -- Observable #4: Li-7 1s hyperfine splitting               [STUB -- next iters]    *)
(* ============================================================================================ *)
(* Z-scaling: Z^3 (contact density) x nuclear factors.  7Li: I=3/2, mu ~ 3.2564 mu_N,           *)
(*   g_I = mu/I ~ 2.171.  GENUINE r_e discriminator (Fermi contact linear in g_s).               *)
(*   Brief target ~12.7 GHz (Beckmann 1974) order-of-magnitude OK (known 7Li2+ 1s HFS ~11.8 GHz).*)

(* ============================================================================================ *)
(* Section 5 -- Joint chi^2 at Z=3                                       [STUB -- final iter]    *)
(* ============================================================================================ *)
(* Once #1-#4 predictions are in: report Li2+-optimal r_e/r_0 and compare to the Z=1 triangulated *)
(*   0.4994205099128317.  Expected: the universal cutoff is optimal (Branch A), since the         *)
(*   framework's cutoff is Z-invariant by construction (Section III.D gating result).             *)

(* -------------------------------------------------------------------------------------------- *)
(* HUMAN ACCEPTANCE (Crocco 2026 substantive-AI disclosure)                                      *)
(* <!-- TODO: human reviews and fills in -- confirms (a) the Z-invariance of r_e/r_0 follows      *)
(*      from DRQM I Section III.D as recorded (cutoff tied to the Z-independent free-electron     *)
(*      a_e), (b) the #1 provenance finding (brief's 2.0000251707 is a Z~8 value, not Li2+;       *)
(*      Sturm 2014 is the 12C5+ electron-mass paper) is correct, and (c) the framework            *)
(*      prediction g_bound(7Li2+) ~ 2.00200 is the right headline number to compare once a        *)
(*      genuine 7Li2+ measurement is sourced. -->                                                 *)
