"""
DRQM I Eq. (III.18): derivation of the anomalous g-factor formula
    g_r = 2 [1 - 4 r_0 / (2 r + r_0)]
from the dual Dirac eigenvalue equation.

Derivation reference:
  Roadmapping/Equation_Verification/Dual_Relativistic_Quantum_Mechanics_I.md#eqs-iii18iii20--three-new-terms-beyond-schrodinger

This scene gives the high-level conceptual flow (not every line of algebra).
The full derivation chain (III.1)-(III.17) is in the verification doc.

Render:
    uv run manim -pql manim_scenes/drqm_eq18_g_factor_derivation.py DRQMGFactorDerivation
"""

from manim import *


class DRQMGFactorDerivation(Scene):
    """Walk from the dual Dirac Hamiltonian to the g_r formula."""

    def construct(self):
        title = Tex(r"\textbf{The dual Dirac equation and the electron $g$-factor}", font_size=38)
        subtitle = Tex(
            r"Gill, Ares de Parga, Morris, Wade (2021), Eqs.\ (III.1)--(III.22)",
            font_size=24,
        )
        subtitle.next_to(title, DOWN, buff=0.3)
        self.play(Write(title), Write(subtitle))
        self.wait(1.0)
        self.play(FadeOut(title), FadeOut(subtitle))

        # ---- Step 1: dual Dirac Hamiltonian ----
        step1 = Tex(r"\textbf{Step 1.}\ Dual Dirac Hamiltonian:", font_size=28).to_edge(UP)
        eq1 = MathTex(
            r"K_D \;=\; \frac{H_D^2}{2mc^2} + \frac{mc^2}{2}, \qquad H_D \;=\; c\,\boldsymbol\alpha\!\cdot\!\boldsymbol\pi + \beta m c^2 + V_0",
            font_size=36,
        )
        self.play(Write(step1))
        self.play(Write(eq1))
        self.wait(1.5)

        # ---- Step 2: expand K_D ----
        step2 = Tex(r"\textbf{Step 2.}\ Expanding $H_D^2$ using the Dirac identities:", font_size=24).to_edge(UP)
        eq2 = MathTex(
            r"K_D = \tfrac{\boldsymbol\pi^2}{2m} + \beta V_0 + mc^2 + \tfrac{V_0\boldsymbol\alpha\!\cdot\!\boldsymbol\pi}{mc}"
            r" - \tfrac{e\hbar\,\boldsymbol\Sigma\!\cdot\!\mathbf{B}}{2mc} - \tfrac{i\hbar\,\boldsymbol\alpha\!\cdot\!\nabla V_0}{2mc} + \tfrac{V_0^2}{2mc^2}",
            font_size=28,
        )
        self.play(Transform(step1, step2))
        self.play(Transform(eq1, eq2))
        self.wait(2.0)

        # ---- Step 3: eigenvalue split into psi1, psi2 ----
        step3 = Tex(
            r"\textbf{Step 3.}\ Splitting $\Psi = [\psi_1, \psi_2]^t$ and eliminating $\psi_2$:",
            font_size=22,
        ).to_edge(UP)
        eq3 = MathTex(
            r"\psi_2 \;=\; \frac{c\,(\boldsymbol\sigma\!\cdot\!\boldsymbol\pi)}{\lambda - V_0 + mc^2}\,\psi_1",
            font_size=36,
        )
        self.play(Transform(step1, step3))
        self.play(Transform(eq1, eq3))
        self.wait(1.8)

        # ---- Step 4: cutoff approximation ----
        step4 = Tex(
            r"\textbf{Step 4.}\ Cutoff approximation: $\lambda - V_0 + mc^2 \approx 2mc^2\!\left(1 + \tfrac{r_0}{2r}\right)$",
            font_size=22,
        ).to_edge(UP)
        eq4 = MathTex(
            r"r_0 \;=\; \frac{e^2}{mc^2} \quad \text{(classical electron radius)}",
            font_size=32,
            color=YELLOW,
        )
        self.play(Transform(step1, step4))
        self.play(Transform(eq1, eq4))
        self.wait(2.0)

        # ---- Step 5: Pauli identity (sigma . pi)^2 = pi^2 - (eh/c) sigma.B ----
        step5 = Tex(
            r"\textbf{Step 5.}\ Pauli identity: $(\boldsymbol\sigma\!\cdot\!\boldsymbol\pi)^2 = \boldsymbol\pi^2 - (e\hbar/c)\,\boldsymbol\sigma\!\cdot\!\mathbf{B}$",
            font_size=22,
        ).to_edge(UP)
        eq5 = Tex(
            r"\textit{Collecting all the new terms generated by the cutoff and Pauli expansions...}",
            font_size=26,
        )
        self.play(Transform(step1, step5))
        self.play(Transform(eq1, eq5))
        self.wait(2.0)

        # ---- Step 6: the g-factor formula ----
        step6 = Tex(
            r"\textbf{Step 6.}\ Reading off the coefficient of $\boldsymbol\sigma\!\cdot\!\mathbf{B}$:",
            font_size=26,
        ).to_edge(UP)
        g_formula = MathTex(
            r"\boxed{\;g_r \;=\; 2\!\left[1 - \frac{4 r_0}{2 r + r_0}\right]\;}",
            font_size=52,
            color=YELLOW,
        )
        self.play(Transform(step1, step6))
        self.play(Transform(eq1, g_formula))
        self.wait(2.5)

        # ---- Step 7: limit checks ----
        step7 = Tex(r"\textbf{Step 7.}\ Limit checks:", font_size=28).to_edge(UP)
        lim1 = MathTex(r"r = r_0/2:\quad g_r = 2(1 - 4/2) = -2", font_size=32)
        lim2 = MathTex(r"r \to 0:\quad g_r = 2(1 - 4) = -6", font_size=32)
        lim_group = VGroup(lim1, lim2).arrange(DOWN, buff=0.4)
        self.play(Transform(step1, step7))
        self.play(Transform(eq1, lim_group))
        self.wait(2.5)

        # ---- Closing: what about experimental g_e? ----
        closing = Tex(
            r"\textit{What value of $r_e/r_0$ reproduces the experimental }$g_e = -2.00231930\dots$\textit{?}",
            font_size=26,
            color=YELLOW,
        ).to_edge(UP)
        next_card = Tex(
            r"$\Rightarrow$ See next scene: \texttt{drqm\_eq22\_g\_factor\_finding}",
            font_size=24,
        )
        self.play(Transform(step1, closing))
        self.play(Transform(eq1, next_card))
        self.wait(3.0)
