"""Generate static Dataview-like index pages for the History campaign.

Reads every `Bibliography/**/*.md` YAML frontmatter and every chapter file, then
emits three static markdown index pages mimicking what the Obsidian Dataview
plugin would produce — for users without the plugin installed:

  - _index_by_year.md       : every bib entry sorted chronologically (with era)
  - _index_by_tag.md         : every bib entry grouped by tag namespace
  - _index_inferred_claims.md: every #inferred and #speculative claim across
                                chapters, with chapter-file anchor links

Idempotent; re-runs as new chapters land.

Usage:
    uv run python Roadmapping/History/_tools/build_dataview_indexes.py
    uv run python Roadmapping/History/_tools/build_dataview_indexes.py --dry-run
"""

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[3]
HISTORY_ROOT = REPO_ROOT / "Roadmapping" / "History"
BIB_ROOT = HISTORY_ROOT / "Bibliography"
FORWARD_ROOT = HISTORY_ROOT / "Forward"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---", re.DOTALL)
CLAIM_TAG_RE = re.compile(r"`#(inferred|speculative)`")
HEADING_RE = re.compile(r"^(#+)\s+(.+?)\s*$", re.MULTILINE)


def parse_frontmatter(md: Path) -> dict:
    text = md.read_text(encoding="utf-8")
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    try:
        return yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        return {}


def collect_bib_entries() -> list[dict]:
    entries = []
    for sub in ("Primary", "Retrospective"):
        d = BIB_ROOT / sub
        if not d.is_dir():
            continue
        for md in sorted(d.glob("*.md")):
            meta = parse_frontmatter(md)
            if not meta:
                continue
            meta["_path"] = str(md.relative_to(REPO_ROOT))
            meta["_kind"] = sub.lower()
            entries.append(meta)
    return entries


def collect_chapters() -> list[Path]:
    files = sorted(HISTORY_ROOT.glob("0*.md"))
    files.extend(sorted(FORWARD_ROOT.glob("0*.md")))
    return files


def find_claims(chapter: Path) -> list[tuple[str, str, int]]:
    """Find every (tag, surrounding-section-heading, line-no) for #inferred/#speculative tags."""
    text = chapter.read_text(encoding="utf-8")
    # Build mapping line-no -> nearest preceding heading.
    headings = []
    for m in HEADING_RE.finditer(text):
        line_no = text[: m.start()].count("\n") + 1
        headings.append((line_no, m.group(2)))
    out = []
    for m in CLAIM_TAG_RE.finditer(text):
        line_no = text[: m.start()].count("\n") + 1
        # Find nearest preceding heading.
        section = "(top)"
        for h_line, h_text in headings:
            if h_line <= line_no:
                section = h_text
            else:
                break
        out.append((m.group(1), section, line_no))
    return out


def render_by_year(entries: list[dict]) -> str:
    by_era = defaultdict(list)
    for e in entries:
        by_era[str(e.get("era", "?"))].append(e)
    for era in by_era:
        by_era[era].sort(key=lambda e: (str(e.get("year", "")), e.get("cite_key", "")))

    lines = [
        "# Bibliography — by year",
        "",
        "*Auto-generated by `_tools/build_dataview_indexes.py`. Do not hand-edit.*",
        "",
    ]
    for era in sorted(by_era.keys()):
        lines.append(f"## Era: {era}")
        lines.append("")
        lines.append("| Year | Cite-key | Title | Type | PDF status |")
        lines.append("|---:|---|---|---|---|")
        for e in by_era[era]:
            title = str(e.get("title", "")).replace("|", "\\|")
            lines.append(
                f"| {e.get('year', '—')} | [[{e.get('cite_key', '?')}]] | "
                f"{title} | {e.get('type', '?')} | {e.get('pdf_status', '?')} |"
            )
        lines.append("")
    return "\n".join(lines)


def render_by_tag(entries: list[dict]) -> str:
    by_tag = defaultdict(list)
    for e in entries:
        for tag in e.get("tags", []) or []:
            by_tag[str(tag)].append(e)

    # Group tags by namespace prefix.
    namespaces = defaultdict(dict)
    for tag, es in by_tag.items():
        if tag.startswith("#era/"):
            ns = "era"
        elif tag.startswith("#thread/"):
            ns = "thread"
        elif tag.startswith("#") and tag.lstrip("#") in ("verified", "inferred", "speculative", "gill-silent"):
            ns = "framework-claim"
        elif tag.startswith("#"):
            ns = "topic"
        else:
            ns = "free-form"
        namespaces[ns][tag] = es

    lines = [
        "# Bibliography — by tag",
        "",
        "*Auto-generated by `_tools/build_dataview_indexes.py`. Do not hand-edit.*",
        "",
    ]
    for ns in ("era", "thread", "framework-claim", "topic", "free-form"):
        if ns not in namespaces:
            continue
        lines.append(f"## Tag namespace: {ns}")
        lines.append("")
        for tag in sorted(namespaces[ns].keys()):
            es = namespaces[ns][tag]
            lines.append(f"### {tag} — {len(es)} entries")
            lines.append("")
            for e in sorted(es, key=lambda x: (str(x.get("year", "")), x.get("cite_key", ""))):
                lines.append(f"- [[{e.get('cite_key', '?')}]] ({e.get('year', '—')}) — {e.get('title', '')}")
            lines.append("")
    return "\n".join(lines)


def render_inferred_claims(chapters: list[Path]) -> str:
    lines = [
        "# Inferred and speculative claims — by chapter",
        "",
        "*Auto-generated by `_tools/build_dataview_indexes.py`. "
        "Lists every `#inferred` and `#speculative` claim across all chapter files. "
        "Click through to the chapter at the cited line for the full context + the "
        "experimental-distinguishability statement.*",
        "",
    ]
    total_inferred = 0
    total_speculative = 0
    for ch in chapters:
        claims = find_claims(ch)
        if not claims:
            continue
        rel = ch.relative_to(REPO_ROOT)
        lines.append(f"## [{ch.stem}]({rel.as_posix()})")
        lines.append("")
        for tag, section, line_no in claims:
            if tag == "inferred":
                total_inferred += 1
            else:
                total_speculative += 1
            lines.append(f"- `#{tag}` at line {line_no} — in section *{section}*.")
        lines.append("")
    lines.insert(2, f"**Totals:** {total_inferred} `#inferred` · {total_speculative} `#speculative`.")
    lines.insert(3, "")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--dry-run", action="store_true", help="print to stdout instead of writing")
    p.add_argument("--output-dir", default=str(HISTORY_ROOT),
                   help=f"directory to write the three index files into (default: {HISTORY_ROOT})")
    args = p.parse_args()

    entries = collect_bib_entries()
    chapters = collect_chapters()
    by_year = render_by_year(entries)
    by_tag = render_by_tag(entries)
    inferred = render_inferred_claims(chapters)

    out_dir = Path(args.output_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    files = [
        (out_dir / "_index_by_year.md", by_year),
        (out_dir / "_index_by_tag.md", by_tag),
        (out_dir / "_index_inferred_claims.md", inferred),
    ]
    for path, content in files:
        if args.dry_run:
            print(f"--- {path} ---")
            print(content[:500] + ("\n[...]" if len(content) > 500 else ""))
        else:
            path.write_text(content, encoding="utf-8")
            print(f"Wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
