"""Generate bibliography.bib from YAML-frontmatter bibliography notes.

Walks every `.md` under `Bibliography/Primary/` and `Bibliography/Retrospective/`,
reads its YAML frontmatter, and emits a single BibTeX file with one entry per note.
The YAML is canonical; `bibliography.bib` is gitignored and regenerable.

Usage:
    uv run python Roadmapping/History/Bibliography/build_bibtex.py
    uv run python Roadmapping/History/Bibliography/build_bibtex.py --dry-run

YAML → BibTeX field mapping:
    type=primary or type=retrospective → @article (default) / @book / @inproceedings / @misc
        chosen by the `bibtex_type` field if present, otherwise @article
    cite_key → BibTeX key (must match filename without extension)
    title, authors, year, journal, volume, issue, pages, doi, url → standard fields
    arxiv_id → eprint (with archivePrefix=arXiv)

A note missing required fields (cite_key, title, authors, year) is skipped with a
warning printed to stderr; the script does not abort.
"""

import argparse
import os
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[3]
BIB_DIR = Path(__file__).resolve().parent
DEFAULT_OUTPUT = BIB_DIR / "bibliography.bib"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---", re.DOTALL)


def parse_frontmatter(md_path: Path) -> dict | None:
    text = md_path.read_text(encoding="utf-8")
    m = FRONTMATTER_RE.match(text)
    if not m:
        return None
    try:
        return yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError as e:
        print(f"YAML error in {md_path}: {e}", file=sys.stderr)
        return None


def format_authors(authors: list[str]) -> str:
    """BibTeX author field: 'Last, First and Last, First'.

    Inputs may already be in either 'First Last' or 'Last, First' form; passes through
    if a comma is present, otherwise splits on the final space.
    """
    formatted = []
    for a in authors:
        if "," in a:
            formatted.append(a.strip())
        else:
            parts = a.strip().split()
            if len(parts) >= 2:
                formatted.append(f"{parts[-1]}, {' '.join(parts[:-1])}")
            else:
                formatted.append(parts[0] if parts else "")
    return " and ".join(formatted)


def entry_for(meta: dict) -> str | None:
    required = ("cite_key", "title", "authors", "year")
    missing = [k for k in required if not meta.get(k)]
    if missing:
        print(f"Skipping {meta.get('cite_key', '?')}: missing {missing}", file=sys.stderr)
        return None

    bib_type = meta.get("bibtex_type", "article")
    cite_key = meta["cite_key"]

    fields = {
        "title": "{" + str(meta["title"]) + "}",
        "author": "{" + format_authors(meta["authors"]) + "}",
        "year": str(meta["year"]),
    }
    for k in ("journal", "volume", "issue", "pages", "doi", "url", "publisher", "address"):
        v = meta.get(k)
        if v not in (None, "", []):
            fields[k] = "{" + str(v) + "}"

    arxiv = meta.get("arxiv_id")
    if arxiv:
        fields["eprint"] = "{" + str(arxiv) + "}"
        fields["archivePrefix"] = "{arXiv}"

    body = ",\n".join(f"  {k} = {v}" for k, v in fields.items())
    return f"@{bib_type}{{{cite_key},\n{body}\n}}\n"


def collect_notes(bib_root: Path) -> list[Path]:
    notes = []
    for sub in ("Primary", "Retrospective"):
        d = bib_root / sub
        if d.is_dir():
            notes.extend(sorted(d.glob("*.md")))
    return notes


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--bib-root", default=str(BIB_DIR),
                        help=f"bibliography root containing Primary/ and Retrospective/ (default: {BIB_DIR})")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT),
                        help=f"output .bib path (default: {DEFAULT_OUTPUT})")
    parser.add_argument("--dry-run", action="store_true",
                        help="print to stdout instead of writing to --output")
    args = parser.parse_args()

    bib_root = Path(args.bib_root).resolve()
    notes = collect_notes(bib_root)
    if not notes:
        print(f"No bibliography notes found under {bib_root}/{{Primary,Retrospective}}", file=sys.stderr)
        return 0

    entries = []
    for n in notes:
        meta = parse_frontmatter(n)
        if not meta:
            print(f"No YAML frontmatter in {n}", file=sys.stderr)
            continue
        if meta.get("cite_key") and meta["cite_key"] != n.stem:
            print(f"WARNING: {n}: cite_key {meta['cite_key']!r} != filename stem {n.stem!r}", file=sys.stderr)
        e = entry_for(meta)
        if e:
            entries.append(e)

    output = (
        "% Auto-generated by Roadmapping/History/Bibliography/build_bibtex.py\n"
        "% Source of truth is the YAML frontmatter under Bibliography/{Primary,Retrospective}/\n\n"
        + "\n".join(entries)
    )

    if args.dry_run:
        sys.stdout.write(output)
    else:
        Path(args.output).write_text(output, encoding="utf-8")
        print(f"Wrote {len(entries)} entries to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
