"""Generate a skeleton bibliography note from a cite-key (and optional DOI).

Emits `Bibliography/Primary/<cite_key>.md` or `Bibliography/Retrospective/<cite_key>.md`
with the full YAML schema documented in `Bibliography/README.md`. Optional `--from-doi`
auto-fills `title`, `authors`, `year`, `journal`, `volume`, `pages` via the Crossref REST
API (https://api.crossref.org/works/<doi>) — no API key required, polite-pool friendly.

Usage:
    uv run python Roadmapping/History/Bibliography/scaffold_bib_note.py \\
        --cite-key maxwell1865_dynamical_theory --type primary

    uv run python Roadmapping/History/Bibliography/scaffold_bib_note.py \\
        --cite-key maxwell1865_dynamical_theory --type primary \\
        --from-doi 10.1098/rstl.1865.0008

    uv run python Roadmapping/History/Bibliography/scaffold_bib_note.py \\
        --cite-key foo1900_bar --type primary --dry-run
"""

import argparse
import json
import sys
from pathlib import Path
from urllib.parse import quote
from urllib.request import Request, urlopen

import yaml

BIB_DIR = Path(__file__).resolve().parent
CROSSREF_URL = "https://api.crossref.org/works/{doi}"
USER_AGENT = "PyPhysics-bibliography-scaffold/0.1 (mailto:morris.trey.j@gmail.com)"


def fetch_crossref(doi: str) -> dict:
    """Hit Crossref for a DOI and return its `message` dict."""
    url = CROSSREF_URL.format(doi=quote(doi, safe="/.()-"))
    req = Request(url, headers={"User-Agent": USER_AGENT})
    with urlopen(req, timeout=15) as resp:
        payload = json.loads(resp.read().decode("utf-8"))
    return payload.get("message", {})


def metadata_from_crossref(msg: dict) -> dict:
    """Translate a Crossref `message` into the bibliography YAML schema."""
    out: dict = {}

    title = msg.get("title")
    if isinstance(title, list) and title:
        out["title"] = title[0]

    authors = []
    for a in msg.get("author", []):
        given = a.get("given", "").strip()
        family = a.get("family", "").strip()
        if given and family:
            authors.append(f"{given} {family}")
        elif family:
            authors.append(family)
        elif a.get("name"):
            authors.append(a["name"])
    if authors:
        out["authors"] = authors

    year_parts = (
        msg.get("issued", {}).get("date-parts")
        or msg.get("published-print", {}).get("date-parts")
        or msg.get("published-online", {}).get("date-parts")
    )
    if year_parts and year_parts[0]:
        out["year"] = year_parts[0][0]

    journal = msg.get("container-title")
    if isinstance(journal, list) and journal:
        out["journal"] = journal[0]

    for k_in, k_out in (("volume", "volume"), ("issue", "issue"), ("page", "pages")):
        if msg.get(k_in):
            out[k_out] = msg[k_in]

    if msg.get("DOI"):
        out["doi"] = msg["DOI"]
    if msg.get("URL"):
        out["url"] = msg["URL"]

    return out


def default_frontmatter(cite_key: str, type_: str) -> dict:
    return {
        "cite_key": cite_key,
        "title": "",
        "authors": [],
        "year": "",
        "type": type_,
        "era": "",
        "tags": [],
        "journal": "",
        "volume": "",
        "issue": "",
        "pages": "",
        "doi": "",
        "url": "",
        "arxiv_id": "",
        "pdf_status": "pending",
        "pdf_path": "",
        "converted_md": "",
        "pages_quoted": "",
        "gill_corpus_overlap": [],
        "chapters_citing": [],
    }


def merge(default: dict, overrides: dict) -> dict:
    out = dict(default)
    for k, v in overrides.items():
        if v not in (None, "", []):
            out[k] = v
    return out


def render_note(meta: dict) -> str:
    yaml_block = yaml.safe_dump(meta, sort_keys=False, allow_unicode=True, default_flow_style=False)
    return (
        f"---\n{yaml_block}---\n\n"
        f"# {meta.get('title') or meta['cite_key']}\n\n"
        "*Skeleton bib note generated by `scaffold_bib_note.py`.* "
        "Fill in: 2–3-paragraph summary (during the chapter's QA pass), `era`, `tags`, "
        "`gill_corpus_overlap`, and any Crossref-missing fields.\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--cite-key", required=True, help="firstauthor + year + slug (snake_case)")
    parser.add_argument("--type", choices=("primary", "retrospective"), required=True,
                        help="bibliography subdirectory")
    parser.add_argument("--from-doi", help="Crossref DOI lookup; auto-fills title/authors/year/journal/etc.")
    parser.add_argument("--title", help="override title")
    parser.add_argument("--author", action="append", default=None,
                        help="override author (repeatable; 'First Last' or 'Last, First')")
    parser.add_argument("--year", type=int, help="override year")
    parser.add_argument("--bib-root", default=str(BIB_DIR),
                        help=f"bibliography root (default: {BIB_DIR})")
    parser.add_argument("--dry-run", action="store_true", help="print to stdout instead of writing")
    parser.add_argument("--force", action="store_true", help="overwrite existing note")
    args = parser.parse_args()

    bib_root = Path(args.bib_root).resolve()
    subdir = "Primary" if args.type == "primary" else "Retrospective"
    out_path = bib_root / subdir / f"{args.cite_key}.md"

    if out_path.exists() and not args.force and not args.dry_run:
        print(f"{out_path} already exists; pass --force to overwrite.", file=sys.stderr)
        return 1

    meta = default_frontmatter(args.cite_key, args.type)

    if args.from_doi:
        try:
            msg = fetch_crossref(args.from_doi)
            meta = merge(meta, metadata_from_crossref(msg))
        except Exception as e:
            print(f"Crossref lookup failed for {args.from_doi}: {e}", file=sys.stderr)
            print("Continuing with empty fields; fill in by hand.", file=sys.stderr)

    overrides: dict = {}
    if args.title:
        overrides["title"] = args.title
    if args.author:
        overrides["authors"] = args.author
    if args.year:
        overrides["year"] = args.year
    if args.from_doi and not overrides.get("doi"):
        overrides["doi"] = args.from_doi
    meta = merge(meta, overrides)

    note = render_note(meta)

    if args.dry_run:
        sys.stdout.write(note)
    else:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(note, encoding="utf-8")
        print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
